# version: "3.8"

services:
  nginx:
    container_name: eazy-dev-nginx
    image: nginx:latest # Use the latest NGINX image
    ports:
      - "80:80" # Map port 80 for the NGINX server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Link the custom NGINX configuration file
    depends_on:
      - express # Ensure Express service is started before
      - peerjs
    restart: always # Automatically restart if the container stops
    networks:
      - eazydev-network # Connect to the shared network
  express:
    container_name: eazy-dev-express
    build:
      context: .
    # volumes:
    #   - .:/app # Mount the current directory into the container
    #   - /app/node_modules # Prevent overwriting node_modules
    working_dir: /app # Set the working directory inside the container
    ports:
      - "3333:3333" # Map port 3333 for the application
    env_file: .env # Load environment variables from the .env file
    # command: npm run dev # Start the application in development mode
    command: pm2-runtime start ecosystem.config.js # Start the application in development mode
    restart: always # Automatically restart if the container stops
    networks:
      - eazydev-network # Connect to the shared network
  peerjs:
    image: peerjs/peerjs-server
    container_name: eazy-dev-peerjs
    restart: always
    ports:
      - "3001:3001"
    command: peerjs --port 3001 --path /peerjs
    networks:
      - eazydev-network

networks:
  eazydev-network:
    driver: bridge # Use a bridge network for service communication
