services:
  nginx:
    container_name: eazy-dev-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express
      - peerjs
    restart: always
    networks:
      - eazydev-network
  express:
    container_name: eazy-dev-express
    build:
      context: .

    working_dir: /app
    ports:
      - "3333:3333"
    env_file: .env
    command: npm start
    restart: always
    networks:
      - eazydev-network
  peerjs:
    image: peerjs/peerjs-server
    container_name: eazy-dev-peerjs
    restart: always
    ports:
      - "3001:3001"
    command: peerjs --port 3001 --path /peerjs
    networks:
      - eazydev-network

networks:
  eazydev-network:
    driver: bridge # Use a bridge network for service communication
