export { GoogleLoginController } from "./google-login.controller";
export { LoginController } from "./login.controller";
export { LogoutController } from "./logout.controller";
export { ResendOtpController } from "./resend-otp.controller";
export { SignupController } from "./signup.controller";
export { VerifyOtpController } from "./verify-otp.controller";
export { ForgotPasswordController } from "./forgot-password.controller";
export { GetResetPasswordPageController } from "./get-reset-password-page.controller";
export { ResetPasswordController } from "./reset-password.controller";
