name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Pull Docker image
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/eazydev-backend:latest

      # Step 2: Delete Old Docker images
      - name: Delete old Docker Images
        run: sudo docker system prune -af

      # Step 3: Deploy with Docker compose
      - name: Deploy with Docker Compose
        run: sudo docker-compose up -d
