# name: CD Pipeline

# on:
#   workflow_run:
#     workflows: ["CI Pipeline"]
#     types:
#       - completed

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#       # Step 1: Stop and remove existing containers
#       - name: Stop and remove existing containers
#         run: |
#           cd /home/ubuntu
#           sudo docker-compose down

#       # Step 3: Remove old Docker image
#       - name: Remove old backend image
#         run: sudo docker rmi hashim6789/eazydev-backend:latest || true

#       # Step 5: Rebuild and run containers
#       - name: Build and start containers
#         run: sudo docker-compose up -d --build
